kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build
    image: node:14
    volumes:
      - name: npmcache
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn config set registry https://registry.npmmirror.com
      - yarn
      - yarn prepare
      - yarn build
    environment:
      CI: false
      GENERATE_SOURCEMAP: false

  - name: deploy
    image: ubuntu:22.04
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/paperplane-share/
      - rm -rf /webroot/paperplane-share/**/*.*
      - cp -rf ./build/* /webroot/paperplane-share/

volumes:
  - name: webroot
    host:
      path: /home/ubuntu/www
  - name: npmcache
    host:
      path: /home/ubuntu/npmcache

trigger:
  branch:
    - master
